[Variables]
IconWidth=80
TvPath=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\TeamViewer.lnk
DiabloPath=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Diablo III\Diablo III.lnk
ExplorerPath=explorer.exe
GptPath=https://chat.openai.com/
GwPath=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\GroupWise\GroupWise.lnk
LogseqPath=C:\Users\Gigabyte\AppData\Local\Programs\Logseq\Logseq.exe
MessengerPath="start shell:appsFolder\FACEBOOK.317180B0BB486_8xx8rvfyw5nnt!App"
SlackPath=C:\Users\szymong\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Slack Technologies Inc\Slack.lnk
VscodePath=C:\Users\szymong\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Visual Studio Code\Visual Studio Code.lnk
CursorPath=C:\Users\szymong\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Cursor\Cursor.lnk
DiscordPath=C:\Users\szymong\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk