[Variables]
TvPath=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\TeamViewer.lnk
DiabloPath=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Diablo III\Diablo III.lnk
ExplorerPath=C:\Program Files\Internet Explorer\iexplore.exe
FirefoxPath=C:\Program Files\Mozilla Firefox\firefox.exe
GptPath=https://chat.openai.com/
GwPath=C:\Program Files\Guild Wars\Gw.exe
LogseqPath=C:\Users\Gigabyte\AppData\Local\Programs\Logseq\Logseq.exe
MessengerPath=https://www.messenger.com/
SlackPath=C:\Users\Gigabyte\AppData\Local\slack\slack.exe
VscodePath=C:\Users\Gigabyte\AppData\Local\Programs\Microsoft VS Code\Code.exe
CursorPath=C:\Users\Gigabyte\AppData\Local\Programs\Cursor\Cursor.exe